name: Trigger auto deployment for mfr-mcp

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/mfr-mcp-AutoDeployTrigger-f8e7ca57-88a7-48d3-b49b-6bad623c617f.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.MFRMCP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.MFRMCP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.MFRMCP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: mfrmcp.azurecr.io
          registryUsername: ${{ secrets.MFRMCP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.MFRMCP_REGISTRY_PASSWORD }}
          containerAppName: mfr-mcp
          resourceGroup: Api-Default-North-Europe
          imageToBuild: mfrmcp.azurecr.io/mfr-mcp:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


